name = "chat-ai-megavault"
compatibility_date = "2024-02-09"

[ai]
binding = "AI"

[build]
command = "npm run build"
publish = "dist"

[site]
bucket = "./dist"

# Add this for Pages
[pages]
pages_build_output_dir = ".output/public" 